import {ChangeEvent,useEffect,useMemo,useState} from 'react'
import {createMockDataset} from './dashboard/mock'
import {loadDatasetFromApi,loadDatasetFromExcel} from './dashboard/dataSource'
import type {DashboardDataset,DataMode,Fund} from './dashboard/types'
import './dashboard/dashboard.css'
import './dashboard/navigation.css'

const pct=(v:number)=>`${v>=0?'+':''}${v.toFixed(2)}%`,money=(v:number)=>`${v.toFixed(2)} 亿元`
function LineChart({a,b}:{a:number[];b:number[]}){const all=[...a,...b],min=Math.min(...all),max=Math.max(...all),path=(s:number[])=>s.map((v,i)=>`${i?'L':'M'}${i/(s.length-1)*100},${94-(v-min)/(max-min||1)*82}`).join(' ');return <svg className="line-chart" viewBox="0 0 100 100" preserveAspectRatio="none"><path d={path(b)} className="benchmark"/><path d={path(a)} className="fundline"/></svg>}
function Bars({items}:{items:{name:string;value:number;benchmark?:number}[]}){const max=Math.max(...items.flatMap(x=>[Math.abs(x.value),Math.abs(x.benchmark??0)]),1);return <div className="bars">{items.map(x=><div className="bar-row" key={x.name}><span>{x.name}</span><div><i style={{width:`${Math.abs(x.value)/max*88}%`}}/><b style={{width:`${Math.abs(x.benchmark??0)/max*88}%`}}/></div><strong>{x.value.toFixed(1)}%</strong></div>)}</div>}
export default function App(){
 const[dataset,setDataset]=useState<DashboardDataset>(createMockDataset()),[selectedCode,setSelectedCode]=useState(dataset.funds[0].code),[mode,setMode]=useState<DataMode>('mock'),[message,setMessage]=useState('演示数据 · 所有产品、行情与持仓均为上市前情景模拟')
 const[activeSection,setActiveSection]=useState('overview')
 const[backendStatus,setBackendStatus]=useState('正在检查数据服务')
 useEffect(()=>{fetch('/api/v2/health').then(r=>r.json()).then((x:{database?:string})=>setBackendStatus(x.database==='available'?'数据库已连接':x.database==='migration-required'?'数据库待迁移':'模拟模式 · 数据库未连接')).catch(()=>setBackendStatus('静态模拟模式'))},[])
 const fund=dataset.funds.find(x=>x.code===selectedCode)??dataset.funds[0]
 const nav=dataset.nav.filter(x=>x.code===fund.code),flows=dataset.flows.filter(x=>x.code===fund.code),holdings=dataset.holdings.filter(x=>x.code===fund.code),sectors=dataset.sectors.filter(x=>x.code===fund.code),factors=dataset.factors.filter(x=>x.code===fund.code)
 const common=useMemo(()=>{const m=new Map<string,{name:string;count:number;weight:number}>();dataset.holdings.forEach(h=>{const x=m.get(h.stockCode)??{name:h.stockName,count:0,weight:0};x.count++;x.weight+=h.weight;m.set(h.stockCode,x)});return [...m.entries()].map(([code,x])=>({code,...x})).sort((a,b)=>b.count-a.count||b.weight-a.weight).slice(0,8)},[dataset])
 const periodRows=[['近1周',fund.returnSinceLaunch*.12,fund.returnSinceLaunch*.10],['近1月',fund.returnSinceLaunch*.46,fund.returnSinceLaunch*.39],['近3月',fund.returnSinceLaunch,fund.returnSinceLaunch-fund.excessReturn],['模拟成立以来',fund.returnSinceLaunch,fund.returnSinceLaunch-fund.excessReturn]] as const
 const drawdown=nav.map((x,i)=>{const peak=Math.max(...nav.slice(0,i+1).map(n=>n.fundIndex));return-(peak-x.fundIndex)/peak*100})
 const overlap=dataset.funds.slice(0,6).map(a=>dataset.funds.slice(0,6).map(b=>{const ah=dataset.holdings.filter(x=>x.code===a.code),bh=dataset.holdings.filter(x=>x.code===b.code);return ah.reduce((s,x)=>s+Math.min(x.weight,bh.find(y=>y.stockCode===x.stockCode)?.weight??0),0)}))
 const attribution=sectors.map((x,i)=>({name:x.sector,value:+((x.weight-x.benchmarkWeight)*(.015+((i%3)-1)*.008)).toFixed(2)})).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value))
 const rebalanceIntensity=holdings.reduce((s,x)=>s+Math.abs(x.change),0),adds=[...holdings].sort((a,b)=>b.change-a.change).slice(0,4),cuts=[...holdings].sort((a,b)=>a.change-b.change).slice(0,4)
 const sizeExposure=factors.find(x=>x.factor==='规模')?.exposure??0,growthTilt=(factors.find(x=>x.factor==='成长')?.exposure??0)-(factors.find(x=>x.factor==='价值')?.exposure??0),styleRow=sizeExposure>.42?0:sizeExposure<-.42?2:1,styleCol=growthTilt<-.35?0:growthTilt>.35?2:1
 const apply=(d:DashboardDataset,m:DataMode)=>{setDataset(d);setSelectedCode(d.funds[0].code);setMode(m);setMessage(`${m==='api'?'API':'Excel'} 数据已加载 · ${d.asOf}`)}
 const api=async()=>{setMessage('正在连接 API…');try{apply(await loadDatasetFromApi(),'api')}catch(e){setMessage(e instanceof Error?e.message:'API 连接失败')}}
 const excel=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{apply(await loadDatasetFromExcel(f),'excel')}catch(x){setMessage(x instanceof Error?x.message:'Excel 解析失败')}e.target.value=''}
 const goTo=(id:string)=>{setActiveSection(id);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});window.history.replaceState(null,'',`#${id}`)}
 return <div className="app-shell"><aside><div className="brand"><img src="/brand/yinhua-fund-logo.png" alt="银华基金 YINHUA FUND"/><span>ACTIVE ETF INTELLIGENCE</span><strong>中国主动 ETF 研究平台</strong></div><nav>{[['overview','市场总览'],['performance','产品表现'],['holdings','持仓与风格'],['flows','资金与份额'],['compare','横向洞察']].map(([id,t])=><button type="button" className={activeSection===id?'active':''} onClick={()=>goTo(id)} key={id}>{t}</button>)}</nav><div className="source-box"><small>当前数据模式</small><strong>{mode==='mock'?'上市前模拟':mode.toUpperCase()}</strong><p>生产环境将由统一数据服务按交易日更新，并保留来源、时点与质量状态。</p></div></aside>
 <main><header><div><div className="eyebrow">CHINA ACTIVE ETF INTELLIGENCE</div><h1>主动 ETF 市场驾驶舱</h1><p>18只产品的表现、组合特征、资金行为与风险暴露统一观察</p></div><div className="actions"><button onClick={api}>连接 API</button><label>导入 Excel<input type="file" accept=".xlsx,.xls,.csv" onChange={excel}/></label></div></header>
 <div className={`notice ${mode}`}>{message}<span>{backendStatus} · 数据截止：{dataset.asOf}</span></div>
 <section id="overview" className="market-strip"><Stat label="覆盖产品" value={`${dataset.funds.length} 只`} note="首批待上市产品"/><Stat label="模拟总规模" value={money(dataset.market.totalAum)} note="资产净值口径"/><Stat label="模拟总份额" value={`${dataset.market.totalShares.toFixed(2)} 亿份`} note="份额变动独立于净值"/><Stat label="近20日净流入" value={money(dataset.market.netFlow20d)} note="份额变动 × 当日NAV" up/><Stat label="规模加权超额" value={pct(dataset.market.weightedExcess)} note="相对各自合同基准" up/></section>
 <section className="toolbar"><div><span>观察产品</span><select value={selectedCode} onChange={e=>setSelectedCode(e.target.value)}>{dataset.funds.map(x=><option value={x.code} key={x.code}>{x.code} · {x.company} · {x.name}</option>)}</select></div><div className="status"><i/>待上市 · 情景模拟</div></section>
 <section id="performance" className="kpis"><Kpi label="模拟规模" value={money(fund.aum)} note={`${fund.shares.toFixed(2)} 亿份`}/><Kpi label="累计收益" value={pct(fund.returnSinceLaunch)} note="分红再投资口径" up/><Kpi label="相对基准超额" value={pct(fund.excessReturn)} note={fund.benchmark} up/><Kpi label="年化波动率" value={`${fund.volatility.toFixed(2)}%`} note="产品绝对风险"/><Kpi label="最大回撤" value={`-${fund.maxDrawdown.toFixed(2)}%`} note="峰值至谷值" down/><Kpi label="近20日组合换手" value={`${fund.turnover20d.toFixed(2)}%`} note="基于每日PCF估算"/></section>
 <section className="grid"><article className="panel span2"><Title title="累计收益与业绩比较基准" sub="基准用于约束投资风格和评价主动收益，并非复制目标"/><div className="legend"><span className="red">基金</span><span>业绩基准</span></div><LineChart a={nav.map(x=>x.fundIndex)} b={nav.map(x=>x.benchmarkIndex)}/></article><article className="panel"><Title title="产品与管理人" sub="评价策略连续性和产品成本"/><Metric label="基金经理" value={fund.managerName}/><Metric label="管理年限" value={`${fund.managerTenure.toFixed(1)} 年`}/><Metric label="策略标签" value={fund.strategy}/><Metric label="综合费率" value={`${fund.expenseRatio.toFixed(2)}%`}/><Metric label="业绩基准" value={fund.benchmark.replace('全收益指数','TR')}/></article>
 <article className="panel"><Title title="主动管理画像" sub="选股差异、组合广度与集中度"/><Metric label="主动份额" value={`${fund.activeShare.toFixed(1)}%`}/><Metric label="持仓证券数" value={`${fund.holdingsCount} 只`}/><Metric label="前十大集中度" value={`${fund.top10Weight.toFixed(1)}%`}/><Metric label="现金仓位" value={`${fund.cashWeight.toFixed(1)}%`}/><Metric label="风格漂移分数" value={fund.styleDrift.toFixed(2)}/></article><article className="panel"><Title title="权益风格箱" sub="市值层级 × 价值/成长倾向"/><div className="style-box">{['大盘价值','大盘均衡','大盘成长','中盘价值','中盘均衡','中盘成长','小盘价值','小盘均衡','小盘成长'].map((x,i)=><i className={i===styleRow*3+styleCol?'selected':''} key={x}>{x}</i>)}</div><p className="method-note">基于当前持仓的规模、价值和成长标准化暴露定位</p></article><article className="panel"><Title title="组合基本面" sub="当前持仓加权特征 vs 业绩基准"/><CompareMetric label="市盈率 PE" p={fund.portfolioPE} b={fund.benchmarkPE} suffix="x"/><CompareMetric label="净资产收益率 ROE" p={fund.portfolioROE} b={fund.benchmarkROE} suffix="%"/><CompareMetric label="盈利增长" p={fund.earningsGrowth} b={fund.benchmarkGrowth} suffix="%"/><div className="compare-legend"><span>组合</span><span>基准</span></div></article><article className="panel"><Title title="数据可信度" sub="专业展示必须同时说明样本和数据状态"/><Metric label="当前模式" value={mode==='mock'?'情景模拟':mode.toUpperCase()}/><Metric label="持仓覆盖率" value="100.0%"/><Metric label="基准映射率" value="98.6%"/><Metric label="最新PCF状态" value={mode==='mock'?'模拟':'已校验'}/><Metric label="计算模型" value="ActiveETF v1.0"/></article>
 <article className="panel span2 table-panel"><Title title="区间收益率与基准对比" sub="观察主动收益是否持续，而非要求贴近基准"/><table><thead><tr><th>观察区间</th><th>产品收益</th><th>基准收益</th><th>主动收益</th></tr></thead><tbody>{periodRows.map(x=><tr key={x[0]}><td><b>{x[0]}</b></td><td className={x[1]>=0?'up':'down'}>{pct(x[1])}</td><td>{pct(x[2])}</td><td className={x[1]-x[2]>=0?'up':'down'}>{pct(x[1]-x[2])}</td></tr>)}</tbody></table></article><article className="panel"><Title title="主动管理有效性" sub="收益质量、选股胜率与下行保护"/><Metric label="夏普比率" value={(fund.returnSinceLaunch/fund.volatility).toFixed(2)}/><Metric label="Sortino比率" value={(fund.returnSinceLaunch/(fund.volatility*.68)).toFixed(2)}/><Metric label="Calmar比率" value={(fund.returnSinceLaunch/fund.maxDrawdown).toFixed(2)}/><Metric label="选股贡献胜率" value={`${fund.selectionHitRate.toFixed(1)}%`}/><Metric label="下行捕获率" value={`${fund.downsideCapture.toFixed(1)}%`}/><Metric label="回撤修复天数" value={`${Math.round(18+fund.maxDrawdown*2.2)} 日`}/></article>
 <article className="panel span2"><Title title="回撤路径与修复" sub="从历史高点计算的水下曲线，识别风险持续时间"/><LineChart a={drawdown} b={drawdown.map(()=>0)}/></article><article className="panel"><Title title="ETF交易与组合容量" sub="一级申赎、二级市场与底层股票流动性"/><Metric label="折溢价" value={pct(fund.premiumDiscount)}/><Metric label="买卖价差" value={`${fund.spreadBps.toFixed(1)} bp`}/><Metric label="日均成交额" value={`${fund.adv.toLocaleString()} 万元`}/><Metric label="高流动性股票覆盖" value={`${fund.liquidityCoverage.toFixed(1)}%`}/><div className="health"><i style={{width:`${fund.liquidityCoverage}%`}}/><span>规则参考：底层股票最近1年成交额应位于市场前80%</span></div></article>
 <article id="holdings" className="panel span2"><Title title="行业配置与基准" sub="组合权重（红）对比基准权重（灰）"/><Bars items={sectors.map(x=>({name:x.sector,value:x.weight,benchmark:x.benchmarkWeight}))}/></article><article className="panel"><Title title="风格因子暴露" sub="标准化暴露，0为市场中性"/><div className="factor-list">{factors.map(x=><div key={x.factor}><span>{x.factor}</span><i className={x.exposure<0?'neg':''} style={{width:`${Math.abs(x.exposure)/1.3*46}%`}}/><strong>{x.exposure.toFixed(2)}</strong></div>)}</div></article>
 <article className="panel"><Title title="行业超额收益归因" sub="主动权重 × 行业相对收益的情景拆解"/>{attribution.map(x=><div className="attribution" key={x.name}><span>{x.name}</span><i className={x.value<0?'negative':''} style={{width:`${Math.max(4,Math.abs(x.value)*210)}px`}}/><strong className={x.value>=0?'up':'down'}>{pct(x.value)}</strong></div>)}</article><article className="panel span2"><Title title="产品持仓重合矩阵" sub="前6只产品共同持仓的最低权重之和；用于识别策略同质化"/><div className="matrix"><span/><>{dataset.funds.slice(0,6).map(x=><b key={x.code}>{x.company.slice(0,2)}</b>)}</>{dataset.funds.slice(0,6).flatMap((x,i)=>[<b key={`${x.code}-h`}>{x.company.slice(0,2)}</b>,...overlap[i].map((v,j)=><i key={`${i}-${j}`} style={{background:`rgba(159,32,38,${Math.min(.08+v/55,.85)})`}}>{v.toFixed(0)}%</i>)])}</div></article>
 <article className="panel span2 table-panel"><Title title="前十大模拟持仓" sub="披露日持仓；变动为相对上一观察期百分点"/><table><thead><tr><th>证券</th><th>行业</th><th>权重</th><th>权重变动</th></tr></thead><tbody>{holdings.map(h=><tr key={h.stockCode}><td><b>{h.stockName}</b><small>{h.stockCode}</small></td><td>{h.sector}</td><td>{h.weight.toFixed(2)}%</td><td className={h.change>=0?'up':'down'}>{pct(h.change)}</td></tr>)}</tbody></table></article>
 <article className="panel span2"><Title title="每日PCF调仓雷达" sub="监测真实组合的增减持方向、调仓强度与风格稳定性"/><div className="rebalance-summary"><Kpi label="当日权重变动总量" value={`${rebalanceIntensity.toFixed(2)} pp`} note="∑|本期权重-上期权重|"/><Kpi label="近20日组合换手" value={`${fund.turnover20d.toFixed(2)}%`} note="避免短期频繁交易"/><Kpi label="风格漂移分数" value={fund.styleDrift.toFixed(2)} note="越低越稳定"/></div><div className="trade-lists"><div><h3>主要增持</h3>{adds.map(x=><Metric key={x.stockCode} label={x.stockName} value={pct(x.change)}/>)}</div><div><h3>主要减持</h3>{cuts.map(x=><Metric key={x.stockCode} label={x.stockName} value={pct(x.change)}/>)}</div></div></article><article className="panel"><Title title="组合规则监测" sub="依据交易所主动ETF业务要求"/><Metric label="持仓不少于30只" value={fund.holdingsCount>=30?'符合':'预警'}/><Metric label="前十大不超过60%" value={fund.top10Weight<=60?'符合':'预警'}/><Metric label="高流动性覆盖" value={fund.liquidityCoverage>=80?'符合':'预警'}/><Metric label="调仓稳定性" value={fund.turnover20d<20?'平稳':'关注'}/><Metric label="风格稳定性" value={fund.styleDrift<.8?'稳定':'偏移'}/></article>
 <article id="flows" className="panel"><Title title="资金与份额监测" sub="区分价格上涨与真实申赎"/><Metric label="当前份额" value={`${fund.shares.toFixed(2)} 亿份`}/><Metric label="20日份额变动" value={pct(fund.sharesChange20d)}/><Metric label="20日估算净流入" value={money(fund.flow20d)}/><Metric label="日均成交额" value={`${fund.adv.toLocaleString()} 万元`}/><Metric label="买卖价差" value={`${fund.spreadBps.toFixed(1)} bp`}/><div className="flow-spark">{flows.map((x,i)=><i key={i} className={x.netFlow<0?'negative':''} style={{height:`${12+Math.abs(x.netFlow)*180}px`}} title={`${x.date}: ${x.netFlow}亿元`}/>)}</div></article>
 <article className="panel"><Title title="市场资金流排名" sub="18只产品近20日估算净申赎"/>{[...dataset.funds].sort((a,b)=>b.flow20d-a.flow20d).slice(0,8).map((x,i)=><div className="rank" key={x.code}><em>{i+1}</em><span><b>{x.company}</b><small>{x.code}</small></span><strong className={x.flow20d>=0?'up':'down'}>{x.flow20d.toFixed(2)}亿</strong></div>)}</article>
 <article id="compare" className="panel span2 table-panel"><Title title="18只产品横向比较" sub="收益、主动风险、规模、流动性与份额统一口径"/><table><thead><tr><th>产品</th><th>公司</th><th>规模</th><th>20日资金流</th><th>份额变动</th><th>累计收益</th><th>超额</th><th>主动份额</th><th>价差</th></tr></thead><tbody>{dataset.funds.map(f=><FundRow key={f.code} f={f}/>)}</tbody></table></article><article className="panel"><Title title="全市场共同重仓" sub="识别18只产品的持仓拥挤与关联"/>{common.map(x=><div className="common" key={x.code}><span><b>{x.name}</b><small>{x.code}</small></span><strong>{x.count} / 18</strong></div>)}</article></section>
 <footer><b>口径与治理：</b> 当前均为虚构情景数据，不代表任何产品真实业绩。主动ETF不以复制指数为目标，业绩比较基准用于评价主动收益和约束风格。正式上线后，日度调仓监测以开市前披露的真实组合PCF为准，并保留披露时间、有效日期和数据来源。</footer></main></div>
}
function Stat({label,value,note,up}:{label:string;value:string;note:string;up?:boolean}){return <div><small>{label}</small><strong className={up?'up':''}>{value}</strong><span>{note}</span></div>}
function Kpi({label,value,note,up,down}:{label:string;value:string;note:string;up?:boolean;down?:boolean}){return <div className="kpi"><small>{label}</small><strong className={up?'up':down?'down':''}>{value}</strong><span>{note}</span></div>}
function Title({title,sub}:{title:string;sub:string}){return <div className="panel-title"><h2>{title}</h2><p>{sub}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function CompareMetric({label,p,b,suffix}:{label:string;p:number;b:number;suffix:string}){return <div className="compare-metric"><span>{label}</span><strong>{p.toFixed(1)}{suffix}</strong><em>{b.toFixed(1)}{suffix}</em></div>}
function FundRow({f}:{f:Fund}){return <tr><td><b>{f.name}</b><small>{f.code}</small></td><td>{f.company}</td><td>{f.aum.toFixed(2)}亿</td><td className={f.flow20d>=0?'up':'down'}>{f.flow20d.toFixed(2)}亿</td><td className={f.sharesChange20d>=0?'up':'down'}>{pct(f.sharesChange20d)}</td><td className="up">{pct(f.returnSinceLaunch)}</td><td className={f.excessReturn>=0?'up':'down'}>{pct(f.excessReturn)}</td><td>{f.activeShare.toFixed(1)}%</td><td>{f.spreadBps.toFixed(1)}bp</td></tr>}
