import {ChangeEvent,useMemo,useState} from 'react'
import {createMockDataset} from './dashboard/mock'
import {loadDatasetFromApi,loadDatasetFromExcel} from './dashboard/dataSource'
import type {DashboardDataset,DataMode,Fund} from './dashboard/types'
import './dashboard/dashboard.css'
import './dashboard/navigation.css'

const pct=(v:number)=>`${v>=0?'+':''}${v.toFixed(2)}%`,money=(v:number)=>`${v.toFixed(2)} 亿元`
function LineChart({a,b}:{a:number[];b:number[]}){const all=[...a,...b],min=Math.min(...all),max=Math.max(...all),path=(s:number[])=>s.map((v,i)=>`${i?'L':'M'}${i/(s.length-1)*100},${94-(v-min)/(max-min||1)*82}`).join(' ');return <svg className="line-chart" viewBox="0 0 100 100" preserveAspectRatio="none"><path d={path(b)} className="benchmark"/><path d={path(a)} className="fundline"/></svg>}
function Bars({items}:{items:{name:string;value:number;benchmark?:number}[]}){const max=Math.max(...items.flatMap(x=>[Math.abs(x.value),Math.abs(x.benchmark??0)]),1);return <div className="bars">{items.map(x=><div className="bar-row" key={x.name}><span>{x.name}</span><div><i style={{width:`${Math.abs(x.value)/max*88}%`}}/><b style={{width:`${Math.abs(x.benchmark??0)/max*88}%`}}/></div><strong>{x.value.toFixed(1)}%</strong></div>)}</div>}
export default function App(){
 const[dataset,setDataset]=useState<DashboardDataset>(createMockDataset()),[selectedCode,setSelectedCode]=useState(dataset.funds[0].code),[mode,setMode]=useState<DataMode>('mock'),[message,setMessage]=useState('演示数据 · 所有产品、行情与持仓均为上市前情景模拟')
 const[activeSection,setActiveSection]=useState('overview')
 const fund=dataset.funds.find(x=>x.code===selectedCode)??dataset.funds[0]
 const nav=dataset.nav.filter(x=>x.code===fund.code),flows=dataset.flows.filter(x=>x.code===fund.code),holdings=dataset.holdings.filter(x=>x.code===fund.code),sectors=dataset.sectors.filter(x=>x.code===fund.code),factors=dataset.factors.filter(x=>x.code===fund.code)
 const common=useMemo(()=>{const m=new Map<string,{name:string;count:number;weight:number}>();dataset.holdings.forEach(h=>{const x=m.get(h.stockCode)??{name:h.stockName,count:0,weight:0};x.count++;x.weight+=h.weight;m.set(h.stockCode,x)});return [...m.entries()].map(([code,x])=>({code,...x})).sort((a,b)=>b.count-a.count||b.weight-a.weight).slice(0,8)},[dataset])
 const periodRows=[['近1周',fund.returnSinceLaunch*.12,fund.returnSinceLaunch*.10],['近1月',fund.returnSinceLaunch*.46,fund.returnSinceLaunch*.39],['近3月',fund.returnSinceLaunch,fund.returnSinceLaunch-fund.excessReturn],['模拟成立以来',fund.returnSinceLaunch,fund.returnSinceLaunch-fund.excessReturn]] as const
 const drawdown=nav.map((x,i)=>{const peak=Math.max(...nav.slice(0,i+1).map(n=>n.fundIndex));return-(peak-x.fundIndex)/peak*100})
 const overlap=dataset.funds.slice(0,6).map(a=>dataset.funds.slice(0,6).map(b=>{const ah=dataset.holdings.filter(x=>x.code===a.code),bh=dataset.holdings.filter(x=>x.code===b.code);return ah.reduce((s,x)=>s+Math.min(x.weight,bh.find(y=>y.stockCode===x.stockCode)?.weight??0),0)}))
 const attribution=sectors.map((x,i)=>({name:x.sector,value:+((x.weight-x.benchmarkWeight)*(.015+((i%3)-1)*.008)).toFixed(2)})).sort((a,b)=>Math.abs(b.value)-Math.abs(a.value))
 const apply=(d:DashboardDataset,m:DataMode)=>{setDataset(d);setSelectedCode(d.funds[0].code);setMode(m);setMessage(`${m==='api'?'API':'Excel'} 数据已加载 · ${d.asOf}`)}
 const api=async()=>{setMessage('正在连接 API…');try{apply(await loadDatasetFromApi(),'api')}catch(e){setMessage(e instanceof Error?e.message:'API 连接失败')}}
 const excel=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{apply(await loadDatasetFromExcel(f),'excel')}catch(x){setMessage(x instanceof Error?x.message:'Excel 解析失败')}e.target.value=''}
 const goTo=(id:string)=>{setActiveSection(id);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});window.history.replaceState(null,'',`#${id}`)}
 return <div className="app-shell"><aside><div className="brand"><img src="/brand/yinhua-fund-logo.png" alt="银华基金 YINHUA FUND"/><span>ACTIVE ETF INTELLIGENCE</span><strong>中国主动 ETF 研究平台</strong></div><nav>{[['overview','市场总览'],['performance','产品表现'],['holdings','持仓与风格'],['flows','资金与份额'],['compare','横向洞察']].map(([id,t])=><button type="button" className={activeSection===id?'active':''} onClick={()=>goTo(id)} key={id}>{t}</button>)}</nav><div className="source-box"><small>当前数据模式</small><strong>{mode==='mock'?'上市前模拟':mode.toUpperCase()}</strong><p>生产环境将由统一数据服务按交易日更新，并保留来源、时点与质量状态。</p></div></aside>
 <main><header><div><div className="eyebrow">CHINA ACTIVE ETF INTELLIGENCE</div><h1>主动 ETF 市场驾驶舱</h1><p>18只产品的表现、组合特征、资金行为与风险暴露统一观察</p></div><div className="actions"><button onClick={api}>连接 API</button><label>导入 Excel<input type="file" accept=".xlsx,.xls,.csv" onChange={excel}/></label></div></header>
 <div className={`notice ${mode}`}>{message}<span>数据截止：{dataset.asOf}</span></div>
 <section id="overview" className="market-strip"><Stat label="覆盖产品" value={`${dataset.funds.length} 只`} note="首批待上市产品"/><Stat label="模拟总规模" value={money(dataset.market.totalAum)} note="资产净值口径"/><Stat label="模拟总份额" value={`${dataset.market.totalShares.toFixed(2)} 亿份`} note="份额变动独立于净值"/><Stat label="近20日净流入" value={money(dataset.market.netFlow20d)} note="份额变动 × 当日NAV" up/><Stat label="规模加权超额" value={pct(dataset.market.weightedExcess)} note="相对各自合同基准" up/></section>
 <section className="toolbar"><div><span>观察产品</span><select value={selectedCode} onChange={e=>setSelectedCode(e.target.value)}>{dataset.funds.map(x=><option value={x.code} key={x.code}>{x.code} · {x.company} · {x.name}</option>)}</select></div><div className="status"><i/>待上市 · 情景模拟</div></section>
 <section id="performance" className="kpis"><Kpi label="模拟规模" value={money(fund.aum)} note={`${fund.shares.toFixed(2)} 亿份`}/><Kpi label="累计收益" value={pct(fund.returnSinceLaunch)} note="分红再投资口径" up/><Kpi label="相对基准超额" value={pct(fund.excessReturn)} note={fund.benchmark} up/><Kpi label="年化波动率" value={`${fund.volatility.toFixed(2)}%`} note="日收益率 × √252"/><Kpi label="最大回撤" value={`-${fund.maxDrawdown.toFixed(2)}%`} note="峰值至谷值" down/><Kpi label="信息比率" value={fund.informationRatio.toFixed(2)} note="上市满60日后启用"/></section>
 <section className="grid"><article className="panel span2"><Title title="累计收益与业绩基准" sub="统一起点=100；模拟日频序列"/><div className="legend"><span className="red">基金</span><span>基准</span></div><LineChart a={nav.map(x=>x.fundIndex)} b={nav.map(x=>x.benchmarkIndex)}/></article><article className="panel"><Title title="主动管理画像" sub="相对合同基准的偏离"/><Metric label="主动份额" value={`${fund.activeShare.toFixed(1)}%`}/><Metric label="跟踪误差" value={`${fund.trackingError.toFixed(2)}%`}/><Metric label="前十大集中度" value={`${fund.top10Weight.toFixed(1)}%`}/><Metric label="策略标签" value={fund.strategy}/></article>
 <article className="panel span2 table-panel"><Title title="区间收益率与基准对比" sub="参考专业回测看板，统一比较不同观察窗口"/><table><thead><tr><th>观察区间</th><th>产品收益</th><th>基准收益</th><th>超额收益</th></tr></thead><tbody>{periodRows.map(x=><tr key={x[0]}><td><b>{x[0]}</b></td><td className={x[1]>=0?'up':'down'}>{pct(x[1])}</td><td>{pct(x[2])}</td><td className={x[1]-x[2]>=0?'up':'down'}>{pct(x[1]-x[2])}</td></tr>)}</tbody></table></article><article className="panel"><Title title="风险调整后绩效" sub="产品与合同基准的可比口径"/><Metric label="夏普比率" value={(fund.returnSinceLaunch/fund.volatility).toFixed(2)}/><Metric label="Sortino比率" value={(fund.returnSinceLaunch/(fund.volatility*.68)).toFixed(2)}/><Metric label="Calmar比率" value={(fund.returnSinceLaunch/fund.maxDrawdown).toFixed(2)}/><Metric label="信息比率" value={fund.informationRatio.toFixed(2)}/><Metric label="回撤修复天数" value={`${Math.round(18+fund.maxDrawdown*2.2)} 日`}/></article>
 <article className="panel span2"><Title title="回撤路径与修复" sub="从历史高点计算的水下曲线，识别风险持续时间"/><LineChart a={drawdown} b={drawdown.map(()=>0)}/></article><article className="panel"><Title title="交易与跟踪质量" sub="一级申赎与二级市场联合诊断"/><Metric label="折溢价" value={pct(fund.premiumDiscount)}/><Metric label="买卖价差" value={`${fund.spreadBps.toFixed(1)} bp`}/><Metric label="日均成交额" value={`${fund.adv.toLocaleString()} 万元`}/><Metric label="跟踪误差" value={`${fund.trackingError.toFixed(2)}%`}/><div className="health"><i style={{width:`${Math.max(18,100-fund.spreadBps*4)}%`}}/><span>流动性健康度 {Math.round(Math.max(18,100-fund.spreadBps*4))}/100</span></div></article>
 <article id="holdings" className="panel span2"><Title title="行业配置与基准" sub="组合权重（红）对比基准权重（灰）"/><Bars items={sectors.map(x=>({name:x.sector,value:x.weight,benchmark:x.benchmarkWeight}))}/></article><article className="panel"><Title title="风格因子暴露" sub="标准化暴露，0为市场中性"/><div className="factor-list">{factors.map(x=><div key={x.factor}><span>{x.factor}</span><i className={x.exposure<0?'neg':''} style={{width:`${Math.abs(x.exposure)/1.3*46}%`}}/><strong>{x.exposure.toFixed(2)}</strong></div>)}</div></article>
 <article className="panel"><Title title="行业超额收益归因" sub="主动权重 × 行业相对收益的情景拆解"/>{attribution.map(x=><div className="attribution" key={x.name}><span>{x.name}</span><i className={x.value<0?'negative':''} style={{width:`${Math.max(4,Math.abs(x.value)*210)}px`}}/><strong className={x.value>=0?'up':'down'}>{pct(x.value)}</strong></div>)}</article><article className="panel span2"><Title title="产品持仓重合矩阵" sub="前6只产品共同持仓的最低权重之和；用于识别策略同质化"/><div className="matrix"><span/><>{dataset.funds.slice(0,6).map(x=><b key={x.code}>{x.company.slice(0,2)}</b>)}</>{dataset.funds.slice(0,6).flatMap((x,i)=>[<b key={`${x.code}-h`}>{x.company.slice(0,2)}</b>,...overlap[i].map((v,j)=><i key={`${i}-${j}`} style={{background:`rgba(159,32,38,${Math.min(.08+v/55,.85)})`}}>{v.toFixed(0)}%</i>)])}</div></article>
 <article className="panel span2 table-panel"><Title title="前十大模拟持仓" sub="披露日持仓；变动为相对上一观察期百分点"/><table><thead><tr><th>证券</th><th>行业</th><th>权重</th><th>权重变动</th></tr></thead><tbody>{holdings.map(h=><tr key={h.stockCode}><td><b>{h.stockName}</b><small>{h.stockCode}</small></td><td>{h.sector}</td><td>{h.weight.toFixed(2)}%</td><td className={h.change>=0?'up':'down'}>{pct(h.change)}</td></tr>)}</tbody></table></article>
 <article id="flows" className="panel"><Title title="资金与份额监测" sub="区分价格上涨与真实申赎"/><Metric label="当前份额" value={`${fund.shares.toFixed(2)} 亿份`}/><Metric label="20日份额变动" value={pct(fund.sharesChange20d)}/><Metric label="20日估算净流入" value={money(fund.flow20d)}/><Metric label="日均成交额" value={`${fund.adv.toLocaleString()} 万元`}/><Metric label="买卖价差" value={`${fund.spreadBps.toFixed(1)} bp`}/><div className="flow-spark">{flows.map((x,i)=><i key={i} className={x.netFlow<0?'negative':''} style={{height:`${12+Math.abs(x.netFlow)*180}px`}} title={`${x.date}: ${x.netFlow}亿元`}/>)}</div></article>
 <article className="panel"><Title title="市场资金流排名" sub="18只产品近20日估算净申赎"/>{[...dataset.funds].sort((a,b)=>b.flow20d-a.flow20d).slice(0,8).map((x,i)=><div className="rank" key={x.code}><em>{i+1}</em><span><b>{x.company}</b><small>{x.code}</small></span><strong className={x.flow20d>=0?'up':'down'}>{x.flow20d.toFixed(2)}亿</strong></div>)}</article>
 <article id="compare" className="panel span2 table-panel"><Title title="18只产品横向比较" sub="收益、主动风险、规模、流动性与份额统一口径"/><table><thead><tr><th>产品</th><th>公司</th><th>规模</th><th>20日资金流</th><th>份额变动</th><th>累计收益</th><th>超额</th><th>主动份额</th><th>价差</th></tr></thead><tbody>{dataset.funds.map(f=><FundRow key={f.code} f={f}/>)}</tbody></table></article><article className="panel"><Title title="全市场共同重仓" sub="识别18只产品的持仓拥挤与关联"/>{common.map(x=><div className="common" key={x.code}><span><b>{x.name}</b><small>{x.code}</small></span><strong>{x.count} / 18</strong></div>)}</article></section>
 <footer><b>口径与治理：</b> 当前均为虚构情景数据，不代表任何产品真实业绩。正式上线后，收益使用复权净值，资金流按份额变动法估算，持仓按可获得日处理；不足60个交易日的年化风险指标标记为“样本不足”。</footer></main></div>
}
function Stat({label,value,note,up}:{label:string;value:string;note:string;up?:boolean}){return <div><small>{label}</small><strong className={up?'up':''}>{value}</strong><span>{note}</span></div>}
function Kpi({label,value,note,up,down}:{label:string;value:string;note:string;up?:boolean;down?:boolean}){return <div className="kpi"><small>{label}</small><strong className={up?'up':down?'down':''}>{value}</strong><span>{note}</span></div>}
function Title({title,sub}:{title:string;sub:string}){return <div className="panel-title"><h2>{title}</h2><p>{sub}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function FundRow({f}:{f:Fund}){return <tr><td><b>{f.name}</b><small>{f.code}</small></td><td>{f.company}</td><td>{f.aum.toFixed(2)}亿</td><td className={f.flow20d>=0?'up':'down'}>{f.flow20d.toFixed(2)}亿</td><td className={f.sharesChange20d>=0?'up':'down'}>{pct(f.sharesChange20d)}</td><td className="up">{pct(f.returnSinceLaunch)}</td><td className={f.excessReturn>=0?'up':'down'}>{pct(f.excessReturn)}</td><td>{f.activeShare.toFixed(1)}%</td><td>{f.spreadBps.toFixed(1)}bp</td></tr>}
